"""Generate synthetic DetectTrace datasets from scenario files (dev only, not packaged).

    uv run python scripts/synthetic/generate.py [--scenario NAME [--out DIR]] [--update-golden]

Without `--scenario` it writes the demo dataset and every test fixture (fixture_specs.py).
A scenario (scenarios/NAME.yaml) gives the classes, base rates, weeks, prompt versions and
the behaviors to inject. The generator writes OTLP traces in the Collector file-exporter
layout (gzip-compressed JSON lines, one resourceSpans batch per line, rotated into a few
files), the analyst verdict CSV, one checklist per class and a ready detecttrace.yaml.
`--update-golden` also rewrites expected.json, expected.html (the dashboard) and
expected-view.json (the dashboard's view model) from a check run on the written files, and each trace format variant's expected_init.yaml from an
`init --yes --dry-run` run on it.

Output depends only on the scenario: randomness comes from `random.Random(seed).random()`
alone, because other `random` helpers changed between Python versions; gzip is written with
mtime 0 and no file name; every collection is written in a fixed order.
"""

import argparse
import csv
import gzip
import hashlib
import io
import json
import random
import re
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

from detecttrace import __version__, conventions
from detecttrace.yaml12 import load_yaml12

REPO_ROOT = Path(__file__).resolve().parents[2]
SCENARIO_DIR = Path(__file__).resolve().parent / "scenarios"
GOLDEN_NAME = "expected.json"
GOLDEN_HTML_NAME = "expected.html"
INIT_GOLDEN_NAME = "expected_init.yaml"
VIEW_GOLDEN_NAME = "expected-view.json"
STYLESHEET_PLACEHOLDER = "/* stylesheet */"
SCRIPT_PLACEHOLDER = "/* script */"
RESULTS_PLACEHOLDER = "{}"
SCRIPT_HASH_PLACEHOLDER = "sha256-SCRIPT"
STYLE_HASH_PLACEHOLDER = "sha256-STYLE"
# Replacements are plain text: none of the placeholders holds a backslash or a group reference.
_DASHBOARD_PLACEHOLDERS = (
    (re.compile(r"<style>.*?</style>", re.S), f"<style>{STYLESHEET_PLACEHOLDER}</style>"),
    (re.compile(r"<script>.*?</script>", re.S), f"<script>{SCRIPT_PLACEHOLDER}</script>"),
    (
        re.compile(r'<script type="application/json" id="dt-results">.*?</script>', re.S),
        f'<script type="application/json" id="dt-results">{RESULTS_PLACEHOLDER}</script>',
    ),
    (re.compile(r"script-src 'sha256-[A-Za-z0-9+/=]+'"), f"script-src '{SCRIPT_HASH_PLACEHOLDER}'"),
    (re.compile(r"style-src 'sha256-[A-Za-z0-9+/=]+'"), f"style-src '{STYLE_HASH_PLACEHOLDER}'"),
)
README_TEXT = (
    "Synthetic demo dataset for `detecttrace demo`.\n"
    "Generated by scripts/synthetic/generate.py from scripts/synthetic/scenarios/demo.yaml;\n"
    "do not edit by hand. Every user, address and network in it is reserved for examples.\n"
)

_NS = 1_000_000_000
_MS = 1_000_000
_WEEK_SECONDS = 7 * 24 * 3600
_DOC_NETWORKS = ("192.0.2", "198.51.100", "203.0.113")
_DOC_AS_FIRST, _DOC_AS_LAST = 64496, 64511
_COUNTRIES = ("DE", "BR", "JP", "ZA", "CA", "NL", "SG", "AU")
_DEPARTMENTS = ("Finance", "Sales", "Engineering", "Legal", "Operations", "Support")
_APP_NAMES = (
    "Example Notes Sync",
    "Example Mail Organizer",
    "Example Calendar Helper",
    "Example File Bridge",
    "Example Survey Tool",
)
_SCOPES_BENIGN = ("User.Read", "Calendars.Read", "offline_access")
_SCOPES_RISKY = ("Mail.ReadWrite", "Files.ReadWrite.All", "Mail.Send", "offline_access")
_KIND_INTERNAL, _KIND_CLIENT = 1, 3
_STATUS_ERROR = 2
# Not in detecttrace.conventions because DetectTrace itself never reads them.
_AGENT_NAME = "gen_ai.agent.name"
_REQUEST_MODEL = "gen_ai.request.model"
_PROVIDER = "gen_ai.provider.name"
_INPUT_TOKENS = "gen_ai.usage.input_tokens"
_OUTPUT_TOKENS = "gen_ai.usage.output_tokens"
_TOOL_CALL_ID = "gen_ai.tool.call.id"
_TOOL_TYPE = "gen_ai.tool.type"
_CHAT = "chat"

Verdict = Literal["true_positive", "false_positive", "benign"]


class _Strict(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class AgentSpec(_Strict):
    name: str
    service_version: str
    model: str


class VersionSpec(_Strict):
    name: str
    first_week: int = Field(ge=1)


class TraceLayout(_Strict):
    files: int = Field(ge=1)
    cases_per_batch: int = Field(ge=1)


class Noise(_Strict):
    skip: float
    narrow: float
    failure: float
    retry: float


class Accuracy(_Strict):
    threat: float
    non_threat: float


class ClassSpec(_Strict):
    name: str
    case_prefix: str
    cases_per_week: int = Field(ge=1)
    true_positive_rate: float
    false_positive_share: float
    tools: tuple[str, ...]


class Behavior(_Strict):
    class_: str = Field(alias="class")
    version: str
    tool: str
    skip: float = 0.0
    narrow: float = 0.0
    missed_threat_close: float = 0.0


class SubAgentSpec(_Strict):
    class_: str = Field(alias="class")
    week: int = Field(ge=1)
    name: str
    tools: tuple[str, ...]


class Scenario(_Strict):
    seed: int
    first_monday: date
    weeks: int = Field(ge=1)
    # Where `--scenario NAME` writes; fixture scenarios have none, their folder is registered.
    output_dir: Path | None = None
    # Where `--update-golden` writes the golden file; without it, next to the data.
    golden_dir: Path | None = None
    has_readme: bool = False
    agent: AgentSpec
    versions: tuple[VersionSpec, ...]
    traces: TraceLayout
    noise: Noise
    agent_accuracy: Accuracy
    classes: tuple[ClassSpec, ...]
    behaviors: tuple[Behavior, ...] = ()
    sub_agent: SubAgentSpec | None = None
    analyst_labels: dict[Verdict, tuple[str, ...]]
    agent_labels: dict[Verdict, str]
    config: dict[str, Any]
    checklists: tuple[dict[str, Any], ...]


def load_scenario(name: str) -> Scenario:
    return Scenario.model_validate(
        load_yaml12(SCENARIO_DIR / f"{name}.yaml", max_bytes=1 << 20, what="scenarios are small")
    )


def generate(scenario: Scenario, out_dir: Path) -> list[Path]:
    """Write every file of the scenario into `out_dir`; return the written paths, sorted."""
    unknown = {tool for spec in scenario.classes for tool in spec.tools} - _TOOLS.keys()
    if unknown:
        raise ValueError(f"the scenario names tools the generator cannot fake: {sorted(unknown)}")
    cases = make_cases(scenario)
    written = [
        *write_traces(scenario, cases, out_dir / "traces"),
        write_verdicts(cases, out_dir / "verdicts.csv"),
        *write_checklists(scenario, out_dir / "checklists"),
        _write_config(scenario, out_dir / "detecttrace.yaml"),
    ]
    if scenario.has_readme:
        written.append(write_text(out_dir / "README.txt", README_TEXT))
    return sorted(written, key=lambda path: path.as_posix())


def update_golden(out_dir: Path, golden_dir: Path) -> list[Path]:
    """Run the check on `out_dir` and write its results and dashboard into `golden_dir`, version
    normalized."""
    # Imported here so generating data never depends on the pipeline being importable.
    from detecttrace.dashboard import render_dashboard
    from detecttrace.pipeline import run_check
    from detecttrace.runconfig import load_run_config

    config_path = out_dir / "detecttrace.yaml"
    results = run_check(load_run_config(config_path), config_path).results
    return [
        write_text(golden_dir / GOLDEN_NAME, to_golden_text(normalize_results(results))),
        write_text(golden_dir / GOLDEN_HTML_NAME, normalize_dashboard(render_dashboard(results))),
        write_text(golden_dir / VIEW_GOLDEN_NAME, to_view_golden_text(results)),
    ]


def to_golden_dir(scenario: Scenario, out_dir: Path) -> Path:
    return REPO_ROOT / scenario.golden_dir if scenario.golden_dir else out_dir


def normalize_results(results: dict[str, object]) -> dict[str, object]:
    """Drop what changes with every release, so the golden file changes only with the numbers."""
    return {**results, "generated_by": "detecttrace"}


def normalize_dashboard(html: str) -> str:
    """Keep only the template's own markup: drop the version from the generator marker and
    the footer, and put placeholders in place of the stylesheet, the script, the results block
    and the two policy hashes. Those parts have tests of their own, and a golden full of them
    would change with every stylesheet or script edit and hide the markup changes."""
    from detecttrace.dashboard import GENERATOR_PREFIX

    text = html.replace(f"{GENERATOR_PREFIX} {__version__}", GENERATOR_PREFIX)
    for pattern, replacement in _DASHBOARD_PLACEHOLDERS:
        text = pattern.sub(replacement, text, count=1)
    return text


def to_golden_text(results: object) -> str:
    return json.dumps(results, ensure_ascii=False, allow_nan=False, indent=1) + "\n"


def to_view_golden_text(results: Mapping[str, object]) -> str:
    """The dashboard view model as the React tests read it, its field order kept."""
    from detecttrace.dashboard_view import build_view, to_view_json

    view = to_view_json(build_view(results))
    return json.dumps(view, ensure_ascii=False, allow_nan=False, indent=2) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate synthetic DetectTrace datasets.")
    parser.add_argument("--scenario", help="write only this scenario (a name in scenarios/)")
    parser.add_argument("--out", type=Path, help="output folder (default: the scenario's)")
    parser.add_argument(
        "--update-golden",
        action="store_true",
        help=f"also rewrite {GOLDEN_NAME}, {GOLDEN_HTML_NAME} and {INIT_GOLDEN_NAME}",
    )
    args = parser.parse_args(argv)
    if args.scenario is None:
        if args.out is not None:
            parser.error("--out needs --scenario")
        paths = _write_everything(args.update_golden)
    else:
        scenario = load_scenario(args.scenario)
        if args.out is None and scenario.output_dir is None:
            parser.error(f"scenario {args.scenario} has no output_dir; give --out")
        out_dir: Path = args.out or REPO_ROOT / (scenario.output_dir or "")
        paths = generate(scenario, out_dir)
        if args.update_golden:
            paths.extend(update_golden(out_dir, to_golden_dir(scenario, out_dir)))
    for path in paths:
        print(path)
    return 0


def _write_everything(should_update_golden: bool) -> list[Path]:
    # Imported here because fixture_specs builds on this module.
    import fixture_specs

    scenario = load_scenario("demo")
    demo_dir = REPO_ROOT / (scenario.output_dir or "")
    paths = generate(scenario, demo_dir)
    if should_update_golden:
        paths.extend(update_golden(demo_dir, to_golden_dir(scenario, demo_dir)))
    for spec in fixture_specs.FIXTURES:
        paths.extend(fixture_specs.write_fixture(spec, fixture_specs.FIXTURE_ROOT))
        if should_update_golden:
            paths.append(fixture_specs.update_fixture_golden(spec, fixture_specs.FIXTURE_ROOT))
            if spec.name in fixture_specs.INIT_VARIANTS:
                paths.append(fixture_specs.update_init_golden(spec, fixture_specs.FIXTURE_ROOT))
            if spec.name in fixture_specs.VIEW_FIXTURES:
                paths.append(fixture_specs.update_view_golden(spec, fixture_specs.FIXTURE_ROOT))
    return paths


class _Rng:
    """The only source of randomness: every draw goes through `random.Random.random()`."""

    def __init__(self, seed: int, part: str) -> None:
        # One stream per part (a class's schedule, one case), so tuning one case's
        # behavior leaves every other case unchanged.
        digest = hashlib.sha256(f"{seed}/{part}".encode()).digest()
        self._random = random.Random(int.from_bytes(digest[:8], "big"))

    def chance(self, probability: float) -> bool:
        return self._random.random() < probability

    def below(self, limit: int) -> int:
        return min(int(self._random.random() * limit), limit - 1)

    def between(self, low: int, high: int) -> int:
        return low + self.below(high - low + 1)

    def pick(self, options: Sequence[Any]) -> Any:
        return options[self.below(len(options))]

    def hex(self, digits: int) -> str:
        return "".join(f"{self.below(1 << 16):04x}" for _ in range(digits // 4))

    def ip(self) -> str:
        return f"{self.pick(_DOC_NETWORKS)}.{self.between(1, 254)}"

    def asn(self) -> int:
        return self.between(_DOC_AS_FIRST, _DOC_AS_LAST)


@dataclass(slots=True)
class _CaseContext:
    alert_class: str
    user: str
    usual_ip: str
    alert_ip: str
    app_id: str
    app_name: str
    is_threat: bool
    alert_ns: int


@dataclass(slots=True)
class _Call:
    tool: str
    is_narrow: bool
    is_failed: bool
    in_sub_agent: bool


@dataclass(slots=True)
class _Case:
    case_id: str
    alert_class: str
    week: int
    version: str
    analyst: Verdict
    analyst_label: str
    agent: Verdict
    start_ns: int
    closed_ns: int = 0
    end_ns: int = 0
    spans: list[dict[str, Any]] = field(default_factory=list)


def make_cases(scenario: Scenario) -> list[_Case]:
    monday = datetime.combine(scenario.first_monday, datetime.min.time(), tzinfo=UTC)
    first_ns = int(monday.timestamp()) * _NS
    cases: list[_Case] = []
    for spec in scenario.classes:
        rng = _Rng(scenario.seed, spec.name)
        # Drawn per class and week first, so numbering follows time within a class.
        starts = sorted(
            (week, first_ns + ((week - 1) * _WEEK_SECONDS + rng.below(_WEEK_SECONDS)) * _NS)
            for week in range(1, scenario.weeks + 1)
            for _ in range(spec.cases_per_week + rng.between(-3, 3))
        )
        sub_agent_week = (
            scenario.sub_agent.week
            if scenario.sub_agent and scenario.sub_agent.class_ == spec.name
            else None
        )
        for number, (week, start_ns) in enumerate(starts, start=1):
            has_sub_agent = week == sub_agent_week
            if has_sub_agent:
                sub_agent_week = None
            cases.append(
                _make_case(
                    _Rng(scenario.seed, f"{spec.case_prefix}-{number:04d}"),
                    scenario,
                    spec,
                    f"{spec.case_prefix}-{number:04d}",
                    week,
                    start_ns,
                    has_sub_agent,
                )
            )
    return sorted(cases, key=lambda case: (case.start_ns, case.case_id))


def _make_case(
    rng: _Rng,
    scenario: Scenario,
    spec: ClassSpec,
    case_id: str,
    week: int,
    start_ns: int,
    has_sub_agent: bool,
) -> _Case:
    version = max(
        (version for version in scenario.versions if version.first_week <= week),
        key=lambda version: version.first_week,
    ).name
    analyst = _draw_analyst(rng, spec)
    labels = scenario.analyst_labels[analyst]
    analyst_label = labels[0] if len(labels) == 1 or rng.chance(0.8) else rng.pick(labels[1:])
    behaviors = [b for b in scenario.behaviors if b.class_ == spec.name and b.version == version]
    sub_tools = scenario.sub_agent.tools if has_sub_agent and scenario.sub_agent else ()
    calls = _plan_calls(rng, scenario.noise, spec.tools, behaviors, sub_tools)
    agent = _draw_agent(rng, scenario.agent_accuracy, analyst, calls, behaviors)
    case = _Case(case_id, spec.name, week, version, analyst, analyst_label, agent, start_ns)
    context = _CaseContext(
        alert_class=spec.name,
        user=f"user{rng.below(10_000):04d}@example.com",
        usual_ip=rng.ip(),
        alert_ip=rng.ip(),
        app_id=_uuid(rng),
        app_name=rng.pick(_APP_NAMES),
        is_threat=analyst == "true_positive",
        alert_ns=start_ns - rng.between(60, 900) * _NS,
    )
    _build_spans(rng, scenario, case, context, calls)
    case.closed_ns = case.end_ns + rng.between(20, 36 * 60) * 60 * _NS
    return case


def _draw_analyst(rng: _Rng, spec: ClassSpec) -> Verdict:
    if rng.chance(spec.true_positive_rate):
        return "true_positive"
    return "false_positive" if rng.chance(spec.false_positive_share) else "benign"


def _plan_calls(
    rng: _Rng,
    noise: Noise,
    tools: Sequence[str],
    behaviors: Sequence[Behavior],
    sub_tools: Sequence[str],
) -> list[_Call]:
    calls: list[_Call] = []
    for tool in tools:
        skip = max((b.skip for b in behaviors if b.tool == tool), default=0.0)
        narrow = max((b.narrow for b in behaviors if b.tool == tool), default=0.0)
        if rng.chance(noise.skip) or rng.chance(skip):
            continue
        is_narrow = rng.chance(noise.narrow) or rng.chance(narrow)
        in_sub_agent = tool in sub_tools
        if rng.chance(noise.failure):
            calls.append(_Call(tool, is_narrow, True, in_sub_agent))
            if not rng.chance(noise.retry):
                continue
        calls.append(_Call(tool, is_narrow, False, in_sub_agent))
    return calls


def _draw_agent(
    rng: _Rng,
    accuracy: Accuracy,
    analyst: Verdict,
    calls: Sequence[_Call],
    behaviors: Sequence[Behavior],
) -> Verdict:
    succeeded = {call.tool for call in calls if not call.is_failed}
    if analyst == "true_positive":
        for behavior in behaviors:
            if behavior.tool not in succeeded and rng.chance(behavior.missed_threat_close):
                return "benign"
        if rng.chance(accuracy.threat):
            return "true_positive"
        return "false_positive"
    if rng.chance(accuracy.non_threat):
        return analyst
    if rng.chance(0.15):
        return "true_positive"
    return "benign" if analyst == "false_positive" else "false_positive"


def _build_spans(
    rng: _Rng, scenario: Scenario, case: _Case, context: _CaseContext, calls: Sequence[_Call]
) -> None:
    trace_id = rng.hex(32)
    root_id = rng.hex(16)
    clock = [case.start_ns + rng.between(2, 9) * _MS]

    def chat(parent_id: str) -> None:
        start = clock[0]
        clock[0] += rng.between(600, 2800) * _MS
        attributes = {
            conventions.OPERATION_ATTRIBUTE: _CHAT,
            _PROVIDER: "example",
            _REQUEST_MODEL: scenario.agent.model,
            _INPUT_TOKENS: rng.between(900, 6000),
            _OUTPUT_TOKENS: rng.between(40, 600),
        }
        name = f"{_CHAT} {scenario.agent.model}"
        case.spans.append(
            _span(trace_id, rng.hex(16), parent_id, name, _KIND_CLIENT, start, clock[0], attributes)
        )
        clock[0] += rng.between(1, 6) * _MS

    def tool(call: _Call, parent_id: str) -> None:
        arguments, result = _TOOLS[call.tool](rng, context, call.is_narrow)
        start = clock[0]
        clock[0] += rng.between(120, 1900) * _MS
        attributes: dict[str, object] = {
            conventions.OPERATION_ATTRIBUTE: conventions.EXECUTE_TOOL,
            conventions.TOOL_NAME: call.tool,
            _TOOL_TYPE: "function",
            _TOOL_CALL_ID: f"call_{rng.hex(24)}",
            conventions.TOOL_CALL_ARGUMENTS: json.dumps(arguments),
        }
        status: dict[str, object] = {}
        if call.is_failed:
            attributes[conventions.ERROR_TYPE] = "timeout"
            status = {"code": _STATUS_ERROR, "message": "upstream request timed out"}
        else:
            attributes[conventions.TOOL_CALL_RESULT] = json.dumps(result)
        name = f"{conventions.EXECUTE_TOOL} {call.tool}"
        case.spans.append(
            _span(
                trace_id,
                rng.hex(16),
                parent_id,
                name,
                _KIND_INTERNAL,
                start,
                clock[0],
                attributes,
                status,
            )
        )
        clock[0] += rng.between(1, 6) * _MS

    chat(root_id)
    main_calls = [call for call in calls if not call.in_sub_agent]
    for index, call in enumerate(main_calls):
        tool(call, root_id)
        if index % 2 == 1:
            chat(root_id)
    sub_calls = [call for call in calls if call.in_sub_agent]
    if sub_calls and scenario.sub_agent:
        sub_id = rng.hex(16)
        sub_start = clock[0]
        chat(sub_id)
        for call in sub_calls:
            tool(call, sub_id)
        chat(sub_id)
        attributes = {
            conventions.OPERATION_ATTRIBUTE: conventions.INVOKE_AGENT,
            _AGENT_NAME: scenario.sub_agent.name,
            _REQUEST_MODEL: scenario.agent.model,
        }
        name = f"{conventions.INVOKE_AGENT} {scenario.sub_agent.name}"
        case.spans.append(
            _span(trace_id, sub_id, root_id, name, _KIND_INTERNAL, sub_start, clock[0], attributes)
        )
    chat(root_id)
    case.end_ns = clock[0] + rng.between(2, 9) * _MS
    attributes = {
        conventions.OPERATION_ATTRIBUTE: conventions.INVOKE_AGENT,
        _AGENT_NAME: scenario.agent.name,
        _REQUEST_MODEL: scenario.agent.model,
        "detecttrace.case_id": case.case_id,
        "detecttrace.alert_class": case.alert_class,
        "detecttrace.verdict": scenario.agent_labels[case.agent],
        "detecttrace.prompt_version": case.version,
    }
    name = f"{conventions.INVOKE_AGENT} {scenario.agent.name}"
    case.spans.append(
        _span(trace_id, root_id, None, name, _KIND_INTERNAL, case.start_ns, case.end_ns, attributes)
    )


def _span(
    trace_id: str,
    span_id: str,
    parent_id: str | None,
    name: str,
    kind: int,
    start_ns: int,
    end_ns: int,
    attributes: Mapping[str, object],
    status: dict[str, object] | None = None,
) -> dict[str, Any]:
    return {
        "traceId": trace_id,
        "spanId": span_id,
        "parentSpanId": parent_id or "",
        "flags": 1,
        "name": name,
        "kind": kind,
        "startTimeUnixNano": str(start_ns),
        "endTimeUnixNano": str(end_ns),
        "attributes": [_to_key_value(key, value) for key, value in attributes.items()],
        "status": status or {},
    }


def _to_key_value(key: str, value: object) -> dict[str, object]:
    if isinstance(value, bool):
        return {"key": key, "value": {"boolValue": value}}
    if isinstance(value, int):
        # OTLP JSON writes 64-bit integers as strings.
        return {"key": key, "value": {"intValue": str(value)}}
    return {"key": key, "value": {"stringValue": str(value)}}


def _uuid(rng: _Rng) -> str:
    text = rng.hex(32)
    return f"{text[:8]}-{text[8:12]}-{text[12:16]}-{text[16:20]}-{text[20:]}"


def _iso(ns: int) -> str:
    return datetime.fromtimestamp(ns // _NS, tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


# Each fake tool returns (arguments, result). `is_narrow` makes the arguments fail the
# checklist rule for that tool, for example a lookback shorter than the playbook asks for.
ToolFaker = Callable[[_Rng, _CaseContext, bool], tuple[dict[str, object], dict[str, object]]]


def _fake_user_profile(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    result = {
        "user": context.user,
        "department": rng.pick(_DEPARTMENTS),
        "account_enabled": True,
        "privileged": rng.chance(0.1),
        "manager": f"user{rng.below(10_000):04d}@example.com",
    }
    return {"user": context.user}, result


def _fake_signin_logs(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    lookback = rng.pick(("6h", "12h")) if is_narrow else rng.pick(("24h", "48h", "7d", "P1D"))
    signins = [
        {
            "time": _iso(context.alert_ns - rng.between(1, 20) * 3600 * _NS),
            "ip": context.usual_ip,
            "country": "US",
            "asn": rng.asn(),
            "result": "success",
        },
        {
            "time": _iso(context.alert_ns),
            "ip": context.alert_ip,
            "country": rng.pick(_COUNTRIES),
            "asn": rng.asn(),
            "result": "success" if context.is_threat or rng.chance(0.7) else "mfa_required",
        },
    ]
    return {"user": context.user, "range": lookback, "limit": 100}, {
        "count": len(signins),
        "signins": signins,
    }


def _fake_query_sentinel(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    if context.alert_class == "oauth_consent":
        lookback = rng.pick(("1d", "12h")) if is_narrow else rng.pick(("3d", "7d", "14d"))
        query = (
            f"AuditLogs | where TimeGenerated > ago({lookback}) "
            f"| where OperationName == 'Consent to application' "
            f"| where TargetResources has '{context.app_id}' | summarize count() by InitiatedBy"
        )
    else:
        lookback = rng.pick(("6h", "12h")) if is_narrow else rng.pick(("1d", "24h", "7d", "30d"))
        query = (
            f"SigninLogs | where TimeGenerated > ago({lookback}) "
            f"| where UserPrincipalName == '{context.user}' "
            f"| summarize count() by IPAddress, Location"
        )
    return {"query": query}, {"row_count": rng.between(1, 40), "truncated": False}


def _fake_mfa_status(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    result = {
        "user": context.user,
        "mfa_registered": not context.is_threat or rng.chance(0.5),
        "methods": [rng.pick(("authenticator_app", "fido2_key", "sms"))],
        "last_mfa_success": _iso(context.alert_ns - rng.between(1, 72) * 3600 * _NS),
    }
    return {"user": context.user}, result


def _fake_ip_reputation(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    score = rng.between(60, 95) if context.is_threat else rng.between(0, 45)
    result = {
        "ip": context.alert_ip,
        "asn": rng.asn(),
        "as_name": f"EXAMPLE-NET-{rng.below(26) + 10:X}",
        "risk_score": score,
        "categories": ["anonymizer"] if score > 70 else [],
    }
    return {"ip": context.alert_ip}, result


def _fake_user_locations(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    days = rng.pick((7, 14)) if is_narrow else rng.pick((30, 60, 90))
    result = {"usual_countries": ["US"], "usual_ips": [context.usual_ip], "travel_events": 0}
    return {"user": context.user, "lookback_days": days}, result


def _fake_oauth_grants(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    hours = rng.pick((4, 12)) if is_narrow else rng.pick((24, 48, 168))
    window = {"start": _iso(context.alert_ns - hours * 3600 * _NS), "end": _iso(context.alert_ns)}
    scopes = _SCOPES_RISKY if context.is_threat else _SCOPES_BENIGN
    grant = {
        "app_id": context.app_id,
        "app_name": context.app_name,
        "scopes": list(scopes[: rng.between(2, len(scopes))]),
        "granted_at": _iso(context.alert_ns),
        "consent_type": "user",
    }
    return {"user": context.user, "window": window}, {"grants": [grant]}


def _fake_app_permissions(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    result = {
        "app_id": context.app_id,
        "publisher_verified": not context.is_threat and rng.chance(0.8),
        "reply_urls": [f"https://app{rng.below(100)}.example.com/callback"],
        "tenant_users_consented": rng.between(1, 40),
    }
    return {"app_id": context.app_id}, result


def _fake_consent_events(
    rng: _Rng, context: _CaseContext, is_narrow: bool
) -> tuple[dict[str, object], dict[str, object]]:
    days = rng.pick((7, 14)) if is_narrow else rng.pick((30, 90))
    result = {
        "events": rng.between(1, 12),
        "first_seen": _iso(context.alert_ns - days * 86400 * _NS),
    }
    return {"app_id": context.app_id, "lookback_days": days}, result


_TOOLS: dict[str, ToolFaker] = {
    "get_user_profile": _fake_user_profile,
    "get_signin_logs": _fake_signin_logs,
    "query_sentinel": _fake_query_sentinel,
    "check_mfa_status": _fake_mfa_status,
    "get_ip_reputation": _fake_ip_reputation,
    "get_user_locations": _fake_user_locations,
    "get_oauth_grants": _fake_oauth_grants,
    "get_app_permissions": _fake_app_permissions,
    "get_consent_events": _fake_consent_events,
}


# Rewrites one span (an OTLP JSON object) as another instrumentation would have written it.
SpanTransform = Callable[[dict[str, Any]], dict[str, Any]]
Compression = Literal["gzip", "zstd", "none"]
_SUFFIXES: dict[Compression, str] = {"gzip": ".gz", "zstd": ".zst", "none": ""}


def write_traces(
    scenario: Scenario,
    cases: Sequence[_Case],
    folder: Path,
    *,
    compression: Compression = "gzip",
    transform: SpanTransform | None = None,
) -> list[Path]:
    """Write the cases as Collector file-exporter output: JSON lines rotated into a few files."""
    lines = [
        (end_ns, json.dumps(document, separators=(",", ":")))
        for end_ns, document in to_trace_documents(scenario, cases, transform)
    ]
    folder.mkdir(parents=True, exist_ok=True)
    # Rotated names carry a timestamp, so files from an earlier run would otherwise linger.
    for stale in folder.glob("traces*.jsonl*"):
        stale.unlink()
    per_file = -(-len(lines) // scenario.traces.files)
    chunks = [lines[first : first + per_file] for first in range(0, len(lines), per_file)]
    paths: list[Path] = []
    suffix = _SUFFIXES[compression]
    for index, chunk in enumerate(chunks):
        # Named as the file exporter rotates: the live file, and older ones stamped at rotation.
        is_live = index == len(chunks) - 1
        stamp = datetime.fromtimestamp(chunk[-1][0] // _NS + 1, tz=UTC).strftime(
            "%Y-%m-%dT%H-%M-%S"
        )
        name = "traces.jsonl" if is_live else f"traces-{stamp}.000.jsonl"
        text = "".join(line + "\n" for _, line in chunk)
        paths.append(write_compressed(folder / (name + suffix), text.encode("utf-8"), compression))
    return paths


def to_trace_documents(
    scenario: Scenario, cases: Sequence[_Case], transform: SpanTransform | None = None
) -> list[tuple[int, dict[str, Any]]]:
    """One OTLP document per batch of cases, with the latest end time in the batch."""
    resource = {
        "attributes": [
            _to_key_value(key, value)
            for key, value in {
                "service.name": scenario.agent.name,
                "service.version": scenario.agent.service_version,
                "deployment.environment.name": "production",
                "telemetry.sdk.language": "python",
                "telemetry.sdk.name": "opentelemetry",
            }.items()
        ]
    }
    scope = {"name": "soc_agent.tracing", "version": "0.4.0"}
    size = scenario.traces.cases_per_batch
    documents: list[tuple[int, dict[str, Any]]] = []
    for first in range(0, len(cases), size):
        batch = cases[first : first + size]
        # The Collector exports spans as they end, so children come before their parents.
        spans = sorted(
            (span for case in batch for span in case.spans),
            key=lambda span: (int(span["endTimeUnixNano"]), span["spanId"]),
        )
        if transform is not None:
            spans = [transform(span) for span in spans]
        document = {
            "resourceSpans": [
                {"resource": resource, "scopeSpans": [{"scope": scope, "spans": spans}]}
            ]
        }
        documents.append((max(case.end_ns for case in batch), document))
    return documents


def write_compressed(path: Path, data: bytes, compression: Compression) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if compression == "gzip":
        with (
            path.open("wb") as raw,
            gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as file,
        ):
            file.write(data)
    elif compression == "zstd":
        # Imported here: zstandard is an optional extra, needed only for the zstd fixture.
        import zstandard

        path.write_bytes(zstandard.ZstdCompressor(level=3).compress(data))
    else:
        path.write_bytes(data)
    return path


def write_verdicts(cases: Sequence[_Case], path: Path) -> Path:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(("case_id", "alert_class", "verdict", "closed_at"))
    # Exported in the order analysts closed the cases, as a case system would.
    for case in sorted(cases, key=lambda case: (case.closed_ns, case.case_id)):
        writer.writerow((case.case_id, case.alert_class, case.analyst_label, _iso(case.closed_ns)))
    return write_text(path, buffer.getvalue())


def write_checklists(scenario: Scenario, folder: Path) -> list[Path]:
    folder.mkdir(parents=True, exist_ok=True)
    header = "# Generic example checklist for the demo, not a curated playbook.\n"
    paths: list[Path] = []
    for checklist in scenario.checklists:
        items = [
            {**item, "args": {path: _FlowMap(rule) for path, rule in item["args"].items()}}
            if "args" in item
            else item
            for item in checklist["items"]
        ]
        text = header + to_yaml({**checklist, "items": items})
        paths.append(write_text(folder / f"{checklist['alert_class']}.yaml", text))
    return paths


def _write_config(scenario: Scenario, path: Path) -> Path:
    header = "# Configuration for the bundled demo. Paths are relative to this file.\n"
    return write_text(path, header + to_yaml(scenario.config))


class _FlowMap(dict[str, Any]):
    """A mapping written on one line, as argument rules are in the checklist docs."""


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(
    _FlowMap,
    lambda dumper, data: dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True),
)


def to_yaml(data: object) -> str:
    return yaml.dump(
        data, Dumper=_Dumper, sort_keys=False, default_flow_style=False, allow_unicode=True
    )


def write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))
    return path


if __name__ == "__main__":
    # Run as the `generate` module, so fixture_specs (which imports it) shares this one copy.
    import generate as generator

    sys.exit(generator.main())
