// Generated by scripts/generate_view_types.py from src/detecttrace/dashboard_view.py.
// Do not edit: change the dataclasses and run `uv run python scripts/generate_view_types.py`.

export type ViewVersion = 1;

export type SourceView = {
  readonly name: string;
  readonly path: string;
};

export type HeaderView = {
  readonly title: string;
  readonly sources: ReadonlyArray<SourceView>;
  readonly cases_text: string;
  readonly period_text: string;
  readonly versions_text: string;
  readonly low_coverage_text: string | null;
};

export type StripView = {
  readonly range_x: number;
  readonly range_width: number;
  readonly point_x: number;
  readonly point_left: number;
  readonly point_width: number;
};

export type MetricView = {
  readonly value: string;
  readonly interval: string | null;
  readonly note: string | null;
  readonly n_text: string;
  readonly few_note: string | null;
  readonly strip: StripView | null;
};

export type VersionRowView = {
  readonly label: string;
  readonly style: string;
  readonly is_all: boolean;
  readonly cases_text: string;
  readonly few_note: string | null;
  readonly completeness: MetricView;
  readonly agreement: MetricView;
  readonly kappa: MetricView;
  readonly dangerous_text: string;
  readonly is_dangerous: boolean;
  readonly tp_without_agent_count: number;
  readonly tp_without_agent_text: string | null;
};

export type SkipColumnView = {
  readonly label: string;
  readonly style: string;
  readonly n_text: string;
  readonly few_note: string | null;
};

export type SkipCellView = {
  readonly rate_text: string;
  readonly count_text: string;
  readonly bar_width: number;
  readonly few_note: string | null;
};

export type SkipRowView = {
  readonly item: string;
  readonly cells: ReadonlyArray<SkipCellView>;
};

export type SkipTableView = {
  readonly steps_text: string;
  readonly columns: ReadonlyArray<SkipColumnView>;
  readonly rows: ReadonlyArray<SkipRowView>;
  readonly empty_text: string | null;
};

export type TrendLineView = {
  readonly style: string;
  readonly scope: string;
  readonly label: string;
  readonly values: ReadonlyArray<number | null>;
  readonly counts: ReadonlyArray<number>;
  readonly few: ReadonlyArray<boolean>;
};

export type TrendTableRowView = {
  readonly week: string;
  readonly cells: ReadonlyArray<string>;
};

export type TrendMetricView = {
  readonly title: string;
  readonly lines: ReadonlyArray<TrendLineView>;
  readonly table_rows: ReadonlyArray<TrendTableRowView>;
  readonly empty_text: string | null;
};

export type TrendView = {
  readonly weeks: ReadonlyArray<string>;
  readonly period_text: string;
  readonly completeness: TrendMetricView;
  readonly agreement: TrendMetricView;
  readonly version_first_weeks: Readonly<Record<string, string>>;
  readonly few_legend_text: string;
};

export type ConfusionCellView = {
  readonly count_text: string;
  readonly heat: string;
  readonly is_dangerous: boolean;
  readonly is_flagged: boolean;
};

export type ConfusionRowView = {
  readonly label: string;
  readonly cells: ReadonlyArray<ConfusionCellView>;
};

export type ConfusionView = {
  readonly n_text: string;
  readonly dangerous_text: string;
  readonly column_labels: ReadonlyArray<string>;
  readonly rows: ReadonlyArray<ConfusionRowView>;
};

export type ClassView = {
  readonly anchor: string;
  readonly name: string;
  readonly cases_text: string;
  readonly versions_text: string;
  readonly pooled_note: string | null;
  readonly rows: ReadonlyArray<VersionRowView>;
  readonly skipped: SkipTableView;
  readonly trend: TrendView;
  readonly confusion: ConfusionView;
};

export type ClassFilterView = {
  readonly class_index: number;
  readonly anchor: string;
  readonly label: string;
};

export type CasesView = {
  readonly total_text: string;
  readonly detail_count_text: string;
  readonly detail_sentence: string;
  readonly class_filters: ReadonlyArray<ClassFilterView>;
};

export type CoverageView = {
  readonly text: string;
  readonly hint: string | null;
  readonly is_low: boolean;
};

export type ExampleView = {
  readonly subject: string;
  readonly detail: string | null;
};

export type NoteView = {
  readonly severity: string;
  readonly severity_label: string;
  readonly count_text: string;
  readonly message: string;
  readonly hint: string;
  readonly examples: ReadonlyArray<ExampleView>;
  readonly more_text: string | null;
};

export type LimitView = {
  readonly term: string;
  readonly text: string;
};

export type ServedView = {
  readonly generation: number;
  readonly updated_at: string;
  readonly held_back_text: string | null;
};

export type CountView = {
  readonly label: string;
  readonly value: string;
};

export type WaitingNoteView = {
  readonly message: string;
  readonly hint: string;
};

export type WaitingView = {
  readonly counts: ReadonlyArray<CountView>;
  readonly notes: ReadonlyArray<WaitingNoteView>;
};

export type DashboardView = {
  readonly header: HeaderView;
  readonly classes: ReadonlyArray<ClassView>;
  readonly cases: CasesView;
  readonly coverage: ReadonlyArray<CoverageView>;
  readonly notes: ReadonlyArray<NoteView>;
  readonly limits: ReadonlyArray<LimitView>;
  readonly served: ServedView | null;
  readonly waiting: WaitingView | null;
};

export type View = { readonly view_version: ViewVersion } & DashboardView;
