// Generated by scripts/generate_view_types.py from src/detecttrace/dashboard_view.py.
// Do not edit: change the dataclasses and run `uv run python scripts/generate_view_types.py`.

export type ViewVersion = 1;

export type SourceView = {
  readonly name: string;
  readonly path: string;
};

export type HeaderView = {
  readonly title: string;
  readonly sources: readonly SourceView[];
  readonly cases_text: string;
  readonly period_text: string;
  readonly versions_text: string;
  readonly low_coverage_text: string | null;
};

export type StripView = {
  readonly range_x: number;
  readonly range_width: number;
  readonly point_x: number;
  readonly point_left: number;
  readonly point_width: number;
};

export type MetricView = {
  readonly value: string;
  readonly interval: string | null;
  readonly note: string | null;
  readonly n_text: string;
  readonly few_note: string | null;
  readonly strip: StripView | null;
};

export type VersionRowView = {
  readonly label: string;
  readonly style: string;
  readonly is_all: boolean;
  readonly cases_text: string;
  readonly few_note: string | null;
  readonly completeness: MetricView;
  readonly agreement: MetricView;
  readonly kappa: MetricView;
  readonly dangerous_text: string;
  readonly is_dangerous: boolean;
  readonly tp_without_agent_count: number;
  readonly tp_without_agent_text: string | null;
};

export type SkipColumnView = {
  readonly label: string;
  readonly style: string;
  readonly n_text: string;
  readonly few_note: string | null;
};

export type SkipCellView = {
  readonly rate_text: string;
  readonly count_text: string;
  readonly bar_width: number;
  readonly few_note: string | null;
};

export type SkipRowView = {
  readonly item: string;
  readonly cells: readonly SkipCellView[];
};

export type SkipTableView = {
  readonly steps_text: string;
  readonly columns: readonly SkipColumnView[];
  readonly rows: readonly SkipRowView[];
  readonly empty_text: string | null;
};

export type TrendLineView = {
  readonly style: string;
  readonly scope: string;
  readonly label: string;
  readonly values: readonly (number | null)[];
  readonly counts: readonly number[];
  readonly few: readonly boolean[];
};

export type TrendTableRowView = {
  readonly week: string;
  readonly cells: readonly string[];
};

export type TrendMetricView = {
  readonly title: string;
  readonly lines: readonly TrendLineView[];
  readonly table_rows: readonly TrendTableRowView[];
  readonly empty_text: string | null;
};

export type TrendView = {
  readonly weeks: readonly string[];
  readonly period_text: string;
  readonly completeness: TrendMetricView;
  readonly agreement: TrendMetricView;
  readonly version_first_weeks: Readonly<Record<string, string>>;
  readonly few_legend_text: string;
};

export type ConfusionCellView = {
  readonly count_text: string;
  readonly heat: string;
  readonly is_dangerous: boolean;
  readonly is_flagged: boolean;
};

export type ConfusionRowView = {
  readonly label: string;
  readonly cells: readonly ConfusionCellView[];
};

export type ConfusionView = {
  readonly n_text: string;
  readonly dangerous_text: string;
  readonly column_labels: readonly string[];
  readonly rows: readonly ConfusionRowView[];
};

export type ClassView = {
  readonly anchor: string;
  readonly name: string;
  readonly cases_text: string;
  readonly versions_text: string;
  readonly pooled_note: string | null;
  readonly rows: readonly VersionRowView[];
  readonly skipped: SkipTableView;
  readonly trend: TrendView;
  readonly confusion: ConfusionView;
};

export type ClassFilterView = {
  readonly class_index: number;
  readonly label: string;
};

export type CasesView = {
  readonly total_text: string;
  readonly detail_count_text: string;
  readonly detail_sentence: string;
  readonly class_filters: readonly ClassFilterView[];
};

export type CoverageView = {
  readonly text: string;
  readonly hint: string | null;
  readonly is_low: boolean;
};

export type ExampleView = {
  readonly subject: string;
  readonly detail: string | null;
};

export type NoteView = {
  readonly severity: string;
  readonly severity_label: string;
  readonly count_text: string;
  readonly message: string;
  readonly hint: string;
  readonly examples: readonly ExampleView[];
  readonly more_text: string | null;
};

export type LimitView = {
  readonly term: string;
  readonly text: string;
};

export type DashboardView = {
  readonly header: HeaderView;
  readonly classes: readonly ClassView[];
  readonly cases: CasesView;
  readonly coverage: readonly CoverageView[];
  readonly notes: readonly NoteView[];
  readonly limits: readonly LimitView[];
};

export type View = { readonly view_version: ViewVersion } & DashboardView;
