"""Generate the React dashboard's TypeScript view types from the Python view dataclasses.

    uv run python scripts/generate_view_types.py            # write dashboard/src/view.d.ts
    uv run python scripts/generate_view_types.py --check    # exit 1 if the file is out of date

`detecttrace.dashboard_view.to_view_json` sends the view to the page as JSON; generating the
types from the same dataclasses keeps the two sides from drifting. Types come out
dependency-first: a depth-first walk from `DashboardView` in field order writes each dataclass
after the ones it refers to, so `DashboardView` comes last. An annotation with no TypeScript
form here fails the run instead of becoming a loose type.
"""

import argparse
import difflib
import sys
import types
from collections.abc import Mapping, Sequence
from dataclasses import fields, is_dataclass
from pathlib import Path
from typing import get_args, get_origin, get_type_hints

from detecttrace.dashboard_view import VIEW_VERSION, DashboardView

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "dashboard" / "src" / "view.d.ts"
HEADER = (
    "// Generated by scripts/generate_view_types.py from src/detecttrace/dashboard_view.py.\n"
    "// Do not edit: change the dataclasses and run "
    "`uv run python scripts/generate_view_types.py`.\n"
)
_SCALARS: Mapping[object, str] = {str: "string", int: "number", float: "number", bool: "boolean"}


def render_view_types() -> str:
    """The text of view.d.ts for the current view dataclasses."""
    blocks = [HEADER, f"export type ViewVersion = {VIEW_VERSION};\n"]
    blocks.extend(_render_type(view_class) for view_class in list_view_classes())
    blocks.append(
        f"export type View = {{ readonly view_version: ViewVersion }} & {DashboardView.__name__};\n"
    )
    return "\n".join(blocks)


def list_view_classes() -> list[type]:
    """Every dataclass reachable from `DashboardView`, each after the dataclasses it uses."""
    ordered: list[type] = []
    _visit(DashboardView, ordered)
    return ordered


def to_typescript(annotation: object, owner: type) -> str:
    """The TypeScript type of a field annotation; `owner` names the class in the error."""
    if annotation in _SCALARS:
        return _SCALARS[annotation]
    if isinstance(annotation, type) and is_dataclass(annotation):
        return annotation.__name__
    origin, arguments = get_origin(annotation), get_args(annotation)
    if origin is types.UnionType and type(None) in arguments:
        rest = [argument for argument in arguments if argument is not type(None)]
        if len(rest) == 1:
            return f"{to_typescript(rest[0], owner)} | null"
    if origin is tuple and len(arguments) == 2 and arguments[1] is Ellipsis:
        return _to_array(arguments[0], owner)
    if origin is list and len(arguments) == 1:
        return _to_array(arguments[0], owner)
    if origin is Mapping and len(arguments) == 2 and arguments[0] is str:
        return f"Readonly<Record<string, {to_typescript(arguments[1], owner)}>>"
    raise TypeError(f"{owner.__name__} has an annotation with no TypeScript form: {annotation!r}")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate dashboard/src/view.d.ts.")
    parser.add_argument(
        "--check", action="store_true", help="compare with the committed file instead of writing"
    )
    args = parser.parse_args(argv)
    text = render_view_types()
    if not args.check:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(text, encoding="utf-8", newline="\n")
        return 0
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if current == text:
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        text.splitlines(keepends=True),
        "dashboard/src/view.d.ts (committed)",
        "dashboard/src/view.d.ts (generated)",
    )
    sys.stderr.write("".join(diff))
    sys.stderr.write(
        "view.d.ts is out of date; run `uv run python scripts/generate_view_types.py`.\n"
    )
    return 1


def _visit(view_class: type, ordered: list[type]) -> None:
    if view_class in ordered:
        return
    for annotation in get_type_hints(view_class).values():
        for used in _list_dataclasses(annotation):
            _visit(used, ordered)
    ordered.append(view_class)


def _list_dataclasses(annotation: object) -> list[type]:
    if isinstance(annotation, type) and is_dataclass(annotation):
        return [annotation]
    return [used for argument in get_args(annotation) for used in _list_dataclasses(argument)]


def _render_type(view_class: type) -> str:
    hints = get_type_hints(view_class)
    lines = [
        f"  readonly {field.name}: {to_typescript(hints[field.name], view_class)};"
        for field in fields(view_class)
    ]
    return f"export type {view_class.__name__} = {{\n" + "\n".join(lines) + "\n};\n"


def _to_array(item: object, owner: type) -> str:
    # The generic form needs no parentheses around a union item or a nested array.
    return f"ReadonlyArray<{to_typescript(item, owner)}>"


if __name__ == "__main__":
    sys.exit(main())
